### ISSUE TITLE
Add functions to write []byte as MessagePack 'str'

### ISSUE THREAD

**Issue by rin01** [tinylib/msgp#104]
Thank you for this extraordinary package.

Would it be possible to add these two functions that write MessagePack 'str' from []byte ?

    func (mw *Writer) WriteStringFromBytes(s []byte) error
and

    func AppendStringFromBytes(b []byte, s []byte) []byte

In our application, all strings are stored in []byte buffers, and not in strings, for better performance.
And converting them to string just to serialize them as MessagePack 'str' is something we want to avoid.
Indeed, we transmit millions and millions of "strings", and the conversion from []byte to string would create a huge volume of garbage.

I also see that the opposite function already exists for reading MessagePack 'str' to []byte.

    func (m *Reader) ReadStringAsBytes(scratch []byte) (b []byte, err error)

But there is no correponding function:

    func ReadStringBytesBytes(b []byte, scratch []byte) (v []byte, o []byte, err error)

**Comment by philhofer** [comment]
Seems totally reasonable. See PR #105.

**Comment by rin01** [comment]
You are great !

#105 is perfect. Thank you very much ;-))))
