### ISSUE TITLE
consider generating structs/methods in a canonical order

### ISSUE THREAD

**Issue by glycerine** [tinylib/msgp#107]
I'm loving tinylib/msgp. Thanks so much for this fabulous library.

A minor nit: running go generate msgp seems to write the structs and methods within the generated code files in a random order, which causes git to think that they've been updated even when they really haven't.

Not a big deal. Can't think of an easy fix off the top of my head. Some kind of internal alphabetical sort before writing perhaps? Or perhaps lexical ordering following that of the source file?

Jason

**Comment by ebfe** [comment]
Sorting by type name in FileSet.PrintTo seems to be enough to get consistent output.

**Comment by glycerine** [comment]
Great! Thank you.
