### ISSUE TITLE
Compatibility problems with appengine

### ISSUE THREAD

**Issue by jfbus** [tinylib/msgp#112]
Multiple errors occur when building for appengine :
`go-app-builder: Failed parsing input: parser: bad import "syscall" in github.com/tinylib/msgp/msgp/advise_linux.go`
`go-app-builder: Failed parsing input: parser: bad import "syscall" in github.com/tinylib/msgp/msgp/file.go`

When testing with `goapp test`, the following error occurs :
`./file_port.go:13: MarshalSizer redeclared in this block` and `file_test.go:53: msgp: too few bytes left to read object`

The first 3 are solved with buildflags, the last one is solved by seeking to 0 between the WriteFile and the ReadFile (the mmap version does not require a Seek, the test does not fail).

PR follows.

**Comment by philhofer** [comment]
Fixed by #113
