### ISSUE TITLE
AppendInt64(b []byte, i int64) fails for i == math.MinInt64

### ISSUE THREAD

**Issue by rin01** [tinylib/msgp#116]
Hello,

        i := int64(math.MinInt64)
        b = msgp.AppendInt64(b, i)

        if x, _, err = msgp.ReadInt64Bytes(b); err != nil {
                log.Fatal(err)
        }

        fmt.Printf("in: %d, out: %d\n", i, x)

result:

        in: -9223372036854775808, out: 0

It is because in file write_bytes.go:78, a := abs(i) will return -9223372036854775808 for i == -9223372036854775808.
abs() doesn't work for math.MinInt64.

**Comment by philhofer** [comment]
Fixed by #117
