### ISSUE TITLE
Is this line in file write.go:63 correct ?

### ISSUE THREAD

**Issue by rin01** [tinylib/msgp#121]
I am just having a glance at the source code, and have a little question.

In file write.go:63, a new byte slice is created.

    func Require(old []byte, extra int) []byte {
	if cap(old)-len(old) >= extra {
		return old
	}
	if len(old) == 0 {
		return make([]byte, 0, extra)
	}
	n := make([]byte, len(old), cap(old)-len(old)+extra) <----- IS IT CORRECT ?
	copy(n, old)
	return n
    }

If you want to create a slice with "extra" capacity, shouldn't it be as follows ?

	n := make([]byte, len(old), len(old)+extra)

**Comment by philhofer** [comment]
Looks wrong to me!

Also, it should probably be doing exponential resizing.
