### ISSUE TITLE
Compatibility detection

### ISSUE THREAD

**Issue by philhofer** [tinylib/msgp#139]
When we generate source output, we should (optionally) generate a file that describes the binary format of each generated 'type.' Then, if someone goes back to alter the type declarations and re-generate the msgp source files, we can print a warning (or fail) if we can determine that the binary representation of one of the type declarations is incompatible with the the code that had been previously generated.

**Comment by glycerine** [comment]
Having been bitten in the past (by data type changes), I'm in complete agreement here. 

In fact, I'm working up a project to do just this: to support capnproto style schema numbering and flatbuffers style field deprecation. 

My proposal is called ZebraPack, and my thoughts, such as they are so far, are written up here, https://github.com/glycerine/zebra.

I did some quick and dirty benchmarking based on `msgp`, and will likely prototype by adding to a `msgp` fork. Let me know if you'd be up for adding schema read/write options to `msgp` directly.

**Comment by glycerine** [comment]
Updated location: https://github.com/glycerine/zebrapack, derived from msgp, is feature complete, and provides for generated schemas. It builds on the excellent foundation of `msgp`.
