### ISSUE TITLE
handling elements from another library - auto import copying

### ISSUE THREAD

**Issue by glycerine** [tinylib/msgp#146]
A fragment from replay.go, where I want to generate the msgp methods for the struct ReplayRequest:

```
import (
    tf "github.com/glycerine/tmframe"
)

//go:generate msgp                                                                                      

type ReplayRequest struct {
    Begin  *tf.Date
    Endx   *tf.Date
    Topics []string
}
```
where tf.Date is defined in a separate file:
https://github.com/glycerine/tmframe/blob/master/date.go#L13

and tf.Date already has the msgp method generation done for it.

Currently I have to hand edit the generated replay_gen.go to import tmframe.

Those hand edits will of course be lost when the file is re-generated.

It would be very helpful to have a way to tell msgp to (manually if not automatically) to import the packages it needs in turn in order to resolve the tf in tf.Date.

Or perhaps there is another way?

**Comment by philhofer** [comment]
Right now the generation step runs `goimports` on the generated code; somehow that loop isn't being closed in your environment. Perhaps its having trouble resolving `tf`?

**Comment by glycerine** [comment]
I imagine so, as tf is alias for a package, so goimports won't be able to guess it.
