### ISSUE TITLE
Can't use import package type

### ISSUE THREAD

**Issue by EricYT** [tinylib/msgp#149]
``` go
import (
  uuid "github.com/satori/go.uuid"
)
type Foo struct {
  Id uuid.UUID `msgp:"id"`
  Value string `msgp:"value"`
}
```
When I use 
```bash
go generate file
```
can not resolve the uuid.UUID type.Is there any way to resolve the problem

**Comment by philhofer** [comment]
The code generator *only* reads the input file, so it won't understand types that are declared outside that file. However, if you generate code for `uuid.UUID`, the generated code will compile and run correctly, as the code generator assumes that externally-defined types have the correct code already generated.

**Comment by philhofer** [comment]
(An alternative is to serialize `[16]byte`, or whatever the underlying type of `uuid.UUID` is, because the code generator understands primitive go types.)

**Comment by EricYT** [comment]
Got it.Thanks
