### ISSUE TITLE
Workaround for types that are defined in another package?

### ISSUE THREAD

**Issue by WillSewell** [tinylib/msgp#158]
I have type aliases defined in another package that is imported by the file that I wish to generate MsgPack Decoders/Encoders for. Something like:

_package1/package1.go_

```
package package1

type SomeType string
```

_package2/package2.go_

```
package package2

import "github.com/me/example/package1"

//go:generate msgp

type SomeStruct struct {
    SomeField package1.SomeType `msg:"some_field"`
}
```

When I run `go generate`, I get

```
======== MessagePack Code Generator =======
>>> Input: "package2.go"
package2.go: SomeStruct: unresolved identifier: package1.SomeType
>>> Wrote and formatted "package2_gen.go"
>>> Wrote and formatted "package2_gen_test.go"
```

This seems like it would be quite a common requirement. Is there any workaround for this other than duplicating the types in `package2`, or only using primitive types, and manually converting them?

**Comment by Dieterbe** [comment]
I have the same problem (in my case i have a type alias for an int in another package)

**Comment by glycerine** [comment]
My workaround: I've added `//go:generate msgp` to the appropriate files in package 1 and run go generate there.

**Comment by immesys** [comment]
I am not sure that workaround works for me. Is there a different solution to this?

**Comment by glycerine** [comment]
you could try `zebrapack -msgp`, as it uses the golang.org/x/tools/go/loader package to resolve types in other packages; read starting from https://github.com/glycerine/zebrapack/blob/master/main.go#L180 if you're curious how it works. But be aware, then your code must compile.

**Comment by klauspost** [comment]
msgp works on a per-file basis. I don't really see that changing.
