### ISSUE TITLE
Embedded fields behavior

### ISSUE THREAD

**Issue by gobwas** [tinylib/msgp#163]
Hello! 

Assume we have these structs:

``` go
type Foo struct {
  Name string
}

type Bar struct {
  Foo
  Surname string
}
```

The `Bar` struct becomes in msgpack:

```
{ "Foo": { "Name": "xxx" }, "Surname": "yyy" }
```

But, imho, `Bar` should become:

```
{ "Name": "xxx", "Surname": "yyy" }
```

P.S. `encoding/json` has [the same behavior](https://play.golang.org/p/K5pB-xBeii).

**Comment by ammario** [comment]
It would've been better to inline it initially.

Changing the behavior now would introduce compatibility issues.

**Comment by shabbyrobe** [comment]
New behaviour could be enabled with an additional directive

**Comment by TCBeliever** [comment]
does this directive implement?
not event seen in wiki

**Comment by dallbee** [comment]
What about a `flatten` attribute?

```go
type Foo struct {
  Name string
}

type Bar struct {
  Foo `msg:"flatten"`
  Surname string
}
```

**Comment by philhofer** [comment]
I'd be happy to review a PR.

**Comment by racketprogram** [comment]
#249

**Comment by dallbee** [comment]
Neat! That's a lot simpler than the approach I had taken. I ended up getting somewhat stuck.
