### ISSUE TITLE
Attempted to decode type "int" with method for "str"

### ISSUE THREAD

**Issue by svperfecta** [tinylib/msgp#173]
Hi All - 

I apologize for the potentially misplace Github issue, but I'm not sure if this is an error on my end somewhere or in the library.

I have a server that serializes a Go struct (Match) to MSGPACK and saves it to S3.

Later, I retrieve it from S3, and send it back to the user.

My integration tests are inconsistent.  If I pull the same data from S3 several times, occasionally the function succeeds and occasionally it fails.  I'm not sure why.  I've isolated the this this code:

```
_, err = match.UnmarshalMsg(b)
```

B is a byte array.

Two subsequent calls to the same function are shown below, the first one succeeds, the second fails.
```
[Request 1] Begin method=GET url=/matches
[Request 1] Complete
[Request 2] Begin method=GET url=/matches
[Request 2] Error=msgp: attempted to decode type "int" with method for "str"
[Request 2] Complete
```

Any help is really appreciated.

**Comment by philhofer** [comment]
Sounds like you're corrupting the data somewhere along the way. Can you log a hex dump of the data each time, to see what it looks like when it succeeds versus fails?
