### ISSUE TITLE
control over which types get code generated

### ISSUE THREAD

**Issue by Dieterbe** [tinylib/msgp#175]
similar to `go:generate stringer -type=myType` directives, it would be nice if with `msgp` we could control which types get generated code.
I have plenty of types (both exported and non-exported) for which generating msgp code just doesn't make sense. i want to pick only the few ones for which it does make sense.

btw: awesome project!

**Comment by philhofer** [comment]
You can use `//msgp:ignore typename` to ignore types in a file.

**Comment by Dieterbe** [comment]
sweet, that works fine. thank you.

**Comment by Dieterbe** [comment]
@philhofer I have taken the liberty to add a section about this on the code generator wiki page

https://github.com/tinylib/msgp/wiki/Using-the-Code-Generator/_compare/a10f2eb648444c0ba60354ed4da97daeb89f52fe...6e05d5c8d1f958d1164db34335c6be6622330b59
