### ISSUE TITLE
How can I deal with nil value

### ISSUE THREAD

**Issue by kuangchanglang** [tinylib/msgp#187]
With [msgpack](https://github.com/vmihailenco/msgpack) package, I can use pointer to pointer as parameter in Unmarshal method.
```go
     type Foo struct{}
     var in, out *Foo
     b, _ := msgpack.Marshal(in)
     msgpack.Unmarshal(b, &out)
```    
But decoding with msgpack is extremely slow.   

I can't find a proper way like this in msgp.

**Comment by glycerine** [comment]
maybe try https://github.com/glycerine/greenpack ? `greenpack` is a fork of `msgp`, so it derives its speed from `msgp`'s code generation logic. It is designed to handle missing values well. All values are omitempty by default. You can use the `-omit-clue` flag to generate classic msgpack encoding, which is less safe but will be compatible with other consumers.

**Comment by klauspost** [comment]
Please reopen with a benchmark example, if that is still an issue.
