### ISSUE TITLE
some time.Time String() expectations may break with go1.9

### ISSUE THREAD

**Issue by glycerine** [tinylib/msgp#190]
Just a heads up about go1.9rc2. I filed a ticket,

https://github.com/golang/go/issues/21485

to discuss the breaking change.

**Comment by glycerine** [comment]
The changes needed in `greenpack` were pretty straightforward. `msgp` test changes should be similar. Here's my patch:

https://github.com/glycerine/greenpack/commit/aa2720e5f84e854d4bfac1d4a6a597b9b39cfa5a

**Comment by klauspost** [comment]
Seems like this was fixed.
