### ISSUE TITLE
Several Generation Issues

### ISSUE THREAD

**Issue by ColtonProvias** [tinylib/msgp#203]
I'm having issues where the code being generated is rather error-filled. Missing elses and forced conversions when shimming are the primary issues.

As an example:

https://gist.github.com/ColtonProvias/c5a020bb8ba42942689d114488568354

Line 24 in sample_gen.go attempts to force a conversion that throws an error during compilation. And just 2 lines above an else is missing in the generated code.

**Comment by klauspost** [comment]
The provided example now works.
