### ISSUE TITLE
Assignments of empty value to blank identifier

### ISSUE THREAD

**Issue by dchenk** [tinylib/msgp#208]
I'm getting decoder functions generated that have seemingly unnecessary instances of empty (newly created) variables being assigned to the blank identifier (`_`). For example, look at the second and third lines in this code:
```
func (z *MyType) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	more code...
}
```
Is that third line supposed to be generated? Should I just cut it out every time it appears?

Thanks

**Comment by philhofer** [comment]
The variable `field` is sometimes used by the generated code, and sometimes not. The `_ = field` line is there to prevent compilation from failing if `field` is unused.

Sometimes the code generator produces ugly or non-idiomatic code. While this is regrettable, it isn't unusual. (Also, `msgp` still generates infinitely more readable code than tools like yacc, bison, flex, ragel, etc., so I don't think we do an unusually bad job of this overall.)

Whether or not you post-process the output of the code generator is up to you, but I would recommend against it unless you've got a reliable tool for it.

**Comment by klauspost** [comment]
I don't see any issue here worth pursuing.
