### ISSUE TITLE
Decoding does not call make for empty maps

### ISSUE THREAD

**Issue by jsnathan** [tinylib/msgp#219]
**Observed behavior**: An empty map inside a struct will be decoded as a nil value

**Expected behavior**: An empty map inside a struct should be decoded as a properly initialized map with make(MapType, 0)

**Details**:

Code of the form
```go
type Example struct {
	Slice []int
	Map   map[string]int
}
```
Will generate code like this for the slice field:
 ```go
if cap(z.Slice) >= int(zb0002) {
	z.Slice = (z.Slice)[:zb0002]
} else {
	z.Slice = make([]int, zb0002)
}
```

which will correctly initialize a slice with len=0 for empty slices.

But it will generate code like this for the map field:

```go
if z.Map == nil && zb0003 > 0 {
	z.Map = make(map[string]int, zb0003)
} else if len(z.Map) > 0 {
	for key, _ := range z.Map {
		delete(z.Map, key)
	}
}
```

Here if the map is empty, make is never called, and the field is left as nil.

This can lead to nil map access operations by code that expects the maps to exist (even if empty) in the decoded data.

**Comment by fillest** [comment]
I have a problem with this too.
At the same time msgp can't decode nil'ed map (msgp.TypeError `msgp: attempted to decode type "nil" with method for "map"`)...

**Comment by erikdubbelboer** [comment]
I'm not sure if this should be fixed. From a performance standpoint it's better not to allocate the empty map. Reading from a nil map is fine it's only writing to it that is an issue. I think the most common case is that you decode something and read from it. I guess if you want to write to some decoded value adding the check if the map is nil is only 3 extra lines of code.

**Comment by fillest** [comment]
We have a case where we need to distinguish between an empty map and absense of data (nil). As I understand (correct me), msgpack spec (and popular encoders..) allows this, being "schema-less". If msgp trades flexibility for performance here, how significant is the gain? If I need to decode nil to nil-map, and if I simultaneously need to decode empty map to empty map, do I have to use two extensions at the moment? If yes, probably it would be better at least to have a flag for decoding empty maps to empty maps to avoid copy-pasting or monkey-patching map decoding code.

**Comment by erikdubbelboer** [comment]
You convinced me. I guess for correctness an empty map in the data should encode to an empty map in Go.

I have created a pull request: #233

**Comment by fillest** [comment]
Thanks
