### ISSUE TITLE
I'm trying to pass msgpack results through bufio client-server connection

### ISSUE THREAD

**Issue by unisqu** [tinylib/msgp#221]
I will be using this code
https://systembash.com/a-simple-go-tcp-server-and-tcp-client/

The readline terminator is a newline "\n"

I would like to msgpack my message before the transfer but my message is pure string at this stage.

Because I dont control user input. (which can be anything during msgpack process) will the message passed have "\n" in it? How do I resolve this issue?

Sorry I'm newbie in this. Thanks in advance for the guidance.

**Comment by erikdubbelboer** [comment]
msgpack messages contain the length of the data that is encoded. So reading it from a socket should only read the required bytes. You don't have to add any terminator yourself.

**Comment by unisqu** [comment]
do you have any examples tcp server-client golang source code using msgpacked data to transfer?

or connector or etc

**Comment by erikdubbelboer** [comment]
I think you can close this issue in favor of https://github.com/tinylib/msgp/issues/222#issuecomment-396803040
