### ISSUE TITLE
How do you use msgp? What's the code for marshall or unmarshall easily?

### ISSUE THREAD

**Issue by unisqu** [tinylib/msgp#222]
I can't seem to find an example tutorial online. What's the fastest way to use msgp marshall and unmarshall code?

**Comment by dchenk** [comment]
Two examples from the docs of my fork of the repo: https://godoc.org/github.com/dchenk/msgp/msgp#example-Decode
https://godoc.org/github.com/dchenk/msgp/msgp#example-Encode

**Comment by unisqu** [comment]
I will be using this code
https://systembash.com/a-simple-go-tcp-server-and-tcp-client/

The readline terminator is a newline "\n"

how do I pass msgpacked data? e.g.
data = { "key" => "value" } <- (pseudocode for struct)

can it be this simple? I've seen Json wrapper for tcp transmission

**Comment by erikdubbelboer** [comment]
You don't do:
```go
message, _ := bufio.NewReader(conn).ReadString('\n')
```
but instead you:
```go
r := msgp.NewReader(conn) // outside of your loop! (it needs to be reused)

for {
    // ...

    var data Data // your struct (make sure you generate the msgp code with the msgp command line tool).
    if err := data.DecodeMsg(r); err != nil {
        panic(err)
    }

    // ...
}
```

**Comment by unisqu** [comment]
i've tried but i dont really understand how it's used
this is using gob encoding, which is easy to implement...

Server
https://pastebin.com/06uNDTp5

Client
https://pastebin.com/yEKEGR9Z

how and where do i changed? i keep getting lots of errors with msgp

is msgp production ready?

**Comment by erikdubbelboer** [comment]
You also have to `go install github.com/tinylib/msgp` to install the command line tool (I assume you have `$GOPATH/bin` in your `$PATH`).

Then in your file with your struct you add `//go:generate msgp` on an empty line and on your command line you run `go generate` so msgp generates the required code to handle your struct.

Something like this for the server: https://play.golang.org/p/QPihVLUazSz

Msgp is very production ready, we have used it for years already to handle thousands of messages per second.

**Comment by unisqu** [comment]
Ok I see the problem now. I will just use gop to transfer and msgpack before and after each gop.

**Comment by erikdubbelboer** [comment]
No you don't want to do that. gob and msgp are competitors, they don't complement each other. Think of msgp as a faster more compatible version of gob. Both of them can encode and decode any data. msgp is just much faster, but because of this also much harder to use.

If you don't need to encode/decode thousands of structs per second and you are only working in Go I would recommend just using gob.
