### ISSUE TITLE
How is the ordinary programmer know what the wiki is talking about?

### ISSUE THREAD

**Issue by unisqu** [tinylib/msgp#223]
https://github.com/tinylib/msgp/wiki 

Come on?! Can someone just write the code where we can all just encode / decode / marshall / unmarshall with msgp???

How do we use it with a working example/demo program???

**Comment by unisqu** [comment]
Not that I'm complaining. Can anyone see a working demo online for this package?
Google "github.com/tinylib/msgp", 91 results... you need to be an astronaut to understand how to use this. Anyone care to give a real life working example of usage?

**Comment by unisqu** [comment]
I have this 
type Message struct {
        a int8 
        d int8 
        t string 
        k string
        v string
}
how do i msgp it?

**Comment by erikdubbelboer** [comment]
You start with:
```bash
go install github.com/tinylib/msgp
```
This will give you the `msgp` command line utility.

Then you run:
```bash
msgp -file yourfile.go
```
which will generate `yourfile_gen.go` which will contain the methods for `Message` (or all other structs defined in `yourfile.go`) to encode and decode its data into the messagepack format.
You can open this file and see which methods it created.

It will create methods like:
```go
func (z *Message) DecodeMsg(dc *msgp.Reader) (err error) {
    // ...
}
```
and:
```go
func (z *Message) EncodeMsg(en *msgp.Writer) (err error) {
    // ...
}
```
As you can see these methods can decode your `Message` from a `msgp.Reader`. And encode your `Message` and write it to a `msgp.Writer`.

Then you look at the documentation of msgp to find out how you get a `msgp.Reader` and `msgp.Writer`. See: https://godoc.org/github.com/tinylib/msgp/msgp

Here you will find that if you have a normal `io.Reader` (which `net.Conn` implements) you can use [`msgp.NewReader`](https://godoc.org/github.com/tinylib/msgp/msgp#NewReader) to create it.
And similar for the Writer.

**Comment by erikdubbelboer** [comment]
All of this is somewhat described in the wiki: https://github.com/tinylib/msgp/wiki/Getting-Started

**Comment by unisqu** [comment]
I didn't expect it to be so complicated. but the optimization is worth the extra work.
I've done "go install github.com/tinylib/msgp"
but I got 
    running "msgp": exec: "msgp": executable file not found in $PATH

**Comment by erikdubbelboer** [comment]
`go install` will install your binaries into `$GOPATH/bin` so you will have to add that to your `$PATH`. How to do this depends on the operating system you are using (I suggest googling it if you don't know this).

**Comment by unisqu** [comment]
I finally installed it and generated the main_test_... go file etc but i realised there's no other documentations online to google for...
e.g. "msgp.NewReader", as can be seen, there's no useful information online.

Do i just copy the functions into main.go? Please make a working example online. A real use case as I've mentioned.

**Comment by erikdubbelboer** [comment]
All the documentation about the Reader is here: https://godoc.org/github.com/tinylib/msgp/msgp#Reader

You don't copy the functions into main. You compile the generated file together with your other files. It sounds like you should probably read up on how to build programs in Go as this has nothing to do with this package. Knowledge of the Go toolchain and things like `$PATH` are implied, they don't need to be explain over and over again with the documentation of every Go package.

**Comment by unisqu** [comment]
it's too difficult without a working example.

**Comment by erikdubbelboer** [comment]
https://github.com/tinylib/msgp/wiki/Getting-Started contains a working example including the commands you have to run to generate the code and examples of how to use the generated code. You can edit that page if you feel like things are missing.
