### ISSUE TITLE
One last try on msgp

### ISSUE THREAD

**Issue by unisqu** [tinylib/msgp#224]
https://pastebin.com/SeifgJHX

i managed to get everything to work until this part
>        bts, err := v.MarshalMsg(nil)

How do I Marshal the QryD values?
I dont know why I can't seem to do the MarshalMsg... what's wrong? Can anyone help?

**Comment by erikdubbelboer** [comment]
What is the error you are getting?

**Comment by unisqu** [comment]
```
./main 
[]
0
Nothing to see here yet!
```
it's supposed to show QryD
>  v := QryD{A: 3, D: 12, T: "sdjakhda", K: "fdgsdg", V: "hhhgfh"}

The problem is, I can't even do fmt.Println(left.A)

**Comment by erikdubbelboer** [comment]
I added comments to your code explaining what it does with `// COMMENT: ` as prefix.

```go
package main

import (
	"fmt"
	"github.com/tinylib/msgp/msgp"
)

//go:generate msgp

type QryD struct {
	A int8
	D int8
	T string
	K string
	V string
}

func main() {
	// COMMENT: So here you create 'v' and set its members.
	v := QryD{A: 3, D: 12, T: "sdjakhda", K: "fdgsdg", V: "hhhgfh"}

	// COMMENT: Here you marshal 'v' into a byte slice called 'bts'
	bts, err := v.MarshalMsg(nil)
	if err != nil {
		//              t.Fatal(err)
	}

	// COMMENT: Here you take the byte slice you just created and read it back into 'v'
	// COMMENT: left contains all the bytes remaining in the slice. But since you didn't add anything else to the slice this will be an empty slice.
	left, err := v.UnmarshalMsg(bts)
	if err != nil {
		//              t.Fatal(err)
	}
	if len(left) > 0 {
		//              t.Errorf("%d bytes left over after UnmarshalMsg(): %q", len(left), left)
		fmt.Println("564635")
	} else {
		// COMMENT: Since there was nothing left in the slice this is the code that will execute and it will obviously print an empty slice and 0.
		fmt.Println(left)
		fmt.Println(len(left))

	}

	// COMMENT: Since 'bts' only contained one object ('v') and this function will skip it, again 'left' will be an empty slice.
	left, err = msgp.Skip(bts)
	if err != nil {
		//              t.Fatal(err)
	}
	if len(left) > 0 {
		//              t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
	}

	fmt.Println("Nothing to see here yet!")
}
```

**Comment by unisqu** [comment]
> left, err := v.UnmarshalMsg(bts)
So how do I UnmarshalMsg to get the value of bts?
I should have done 
> left, err := bts.UnmarshalMsg(nil)
??

**Comment by erikdubbelboer** [comment]
```go
var foo QryD
left, err := foo.UnmarshalMsg(bts)
```
Now `left` contains the bytes that are left after taking the object from `bts` and `foo` will contain the exact same values as `v` did when you did `bts, err := v.MarshalMsg(nil)`.

`UnmarshalMsg` just takes the first object in its byte slice argument and tries to put its values into the object you are calling `UnmarshalMsg` on.

**Comment by unisqu** [comment]
https://pastebin.com/P3Q5UNsp

I did the change, i did 
> go build main.go main_gen.go

**Results**
./main 
[]
0
Nothing to see here yet!

I was expecting to see the results of the QryD entries.
original struct to create those main_test_go etc files...

type QryD struct {
	A int8
	D int8
	T string
	K string
	V string
}

What went wrong?

**Comment by erikdubbelboer** [comment]
Explain to me why you would expect it to print anything?

Yes `foo` now contains all the values, but you never print that. You only print `left` which as I explained is empty.

If you want to see the bytes of the marshaled value than print `bts`.

Right now you are just putting `v` into bytes, then taking it out again (into `foo`) and printing what is left which is obviously nothing.

**Comment by unisqu** [comment]
Finally got it to work! Thanks! I'll post the working example on the wiki. Thanks a lot!

Sorry about the questioning coz it's really different from the many packages I've used before. Thanks anyway. Really appreciate it.

**Comment by unisqu** [comment]
OK, in that case, the reason why I used Marshal instead of Encode is because Marshal and unMarshal is more balanced (in terms of speed) than Encode / Decode.

So in any sense, other than the obvious "append" mode of Marshal, is there any advantage to use Encode/Decode other than the difference in speed?

**Comment by unisqu** [comment]
Appreciate all the help. I've done, can be improved but this should be useful for other newbies. Thanks.
https://github.com/tinylib/msgp/wiki/Working-Demo

**Comment by erikdubbelboer** [comment]
Marshal will give you back a byte slice so the result has to fit in memory. Encode will write the result to the io.Writer so it doesn't have to fit in memory. You could for example Encode a huge object to a file on disk, or to a network socket without having to have the whole encoded object in memory.
