### ISSUE TITLE
How do I use MarshalMsg and UnmarshalMsg instead over the wire?

### ISSUE THREAD

**Issue by unisqu** [tinylib/msgp#226]
I can't get Encode / Decode over the wire but I would actually want Marshall/Unmarshall
Client
https://pastebin.com/h24sqVtn

Server
https://pastebin.com/Hn6P7THT

Doesnt work with error : 
:68:42: cannot use reader (type *msgp.Reader) as type []byte in argument to message.UnmarshalMsg

What's the problem?

p.s. : I'm more than happy to write the wiki for this purpose. Thanks in advance.

**Comment by unisqu** [comment]
I understand that. The reason I would want to use Marshall is because I would like to use other programming languages' connect msgpack to transfer data and I'm sure that they will support Marshall more. So is Marshall an option?

**Comment by erikdubbelboer** [comment]
Marshall and Encode do the exact same thing but Marshall returns a byte slice and Encode writes the output to a writer. What you are saying makes no sense. It’s both msgpack encoding.

**Comment by unisqu** [comment]
ok. got it. thanks.
