### ISSUE TITLE
Use "official" sentinel for golang generated code 

### ISSUE THREAD

**Issue by client9** [tinylib/msgp#229]
Hi Team MSGP

The current sentinel for MSGP generated code is

```
// NOTE: THIS FILE WAS PRODUCED BY THE
// MSGP CODE GENERATION TOOL (github.com/tinylib/msgp)
// DO NOT EDIT
```

Turns out there is now an official golang sentinel for generated code.  This allows linters to ignore the generated code and other goodies.

See:

https://golang.org/s/generatedcode 

But to save you the click through, it's just this:

```
Generated files are marked by a line of text that matches the regular expression, in Go syntax:
^// Code generated .* DO NOT EDIT\.$
The .* means the tool can put whatever folderol it wants in there, but the comment must be a single line and must start with Code generated and end with DO NOT EDIT., with a period.

The text may appear anywhere in the file.
```

Happy to do a PR

regards,

n

**Comment by philhofer** [comment]
If you open a PR, I'll merge it. Thanks!

**Comment by client9** [comment]
The PR (forthcoming) will change this to:

```
// Code generated by github.com/tinylib/msgp DO NOT EDIT.
```

Counter-offers welcome

**Comment by client9** [comment]
ready for review.
