### ISSUE TITLE
Could you please create new tag release?

### ISSUE THREAD

**Issue by FZambia** [tinylib/msgp#242]
Hello! We have problems with `dep` dependency resolution with `/github.com/fluent/fluent-logger-golang` which uses this library:

```
vendor/github.com/fluent/fluent-logger-golang/fluent/proto_gen.go:16:9: undefined: msgp.WrapError
```

The problem is because `dep` resolves transitive dependency `github.com/fluent/fluent-logger-golang` into v1.4.0 and `msgp` into v1.0.2 version.

Looks like if you make a new tag release problems should go away. At moment we fixed this issue for us in this way in `Gopkg.toml`:

```
[[override]]
  name = "github.com/fluent/fluent-logger-golang"
  version = "=1.3.0"
```

Alternatively this also works for us:

```
[[override]]
  name = "github.com/tinylib/msgp"
  branch = "master"
```

Thanks!

**Comment by philhofer** [comment]
Done. Use v1.1.0. Thanks!
