### ISSUE TITLE
Fail to decode string encoded as bin type

### ISSUE THREAD

**Issue by sudeep9** [tinylib/msgp#243]
**Problem** 
msgp fails to decode string which were encoded as 'bin' type. It fails with the error: *msgp: too few bytes left to read object*

**Steps to reproduce:**

The following program generates the said error.

Note: The byte buffer is a valid msgpack buffer generated using embedded python program. Notice the use of "use_bin_type=True". When false, this error does not occur

```go
package main

import (
	"fmt"
	"os"
)


var buf = []byte{130, 196, 1, 97, 1, 196, 1, 98, 2}
// The above byte buffer was generated using the following python program
/*
import msgpack

m = {
		'a': 1,
		'b': 2,
}

buf = msgpack.dumps(m, use_bin_type=True)
print "[]byte{%s}" % ",".join([str(ord(n)) for n in buf])
*/

//go:generate msgp

type M struct {
	A int `msgp:"a"`
	B int `msgp:"b"`
}

func main() {
	m := &M{}
	_, err := m.UnmarshalMsg(buf[:])
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	fmt.Printf("%v\n", m)
}

```

**Comment by sudeep9** [comment]
Based on the limited scanning of the code, it seems the issue is in the function: `func ReadStringZC(b []byte) (v []byte, o []byte, err error)` at following place:

https://github.com/tinylib/msgp/blob/af6442a0fcf6e2a1b824f70dd0c734f01e817751/msgp/read_bytes.go#L869

The function returns early in the switch case (due to strings encoded as 'bin') without consuming the buffer and the return variables `v` & `o` are returned with their zero value i.e. `nil`

As a result, the buffer passed to the function `ReadBytesZC(b)` called in `func ReadMapKeyZC(b []byte) ([]byte, []byte, error)` is `nil`

Let me know if this correct then I will raise a PR

**Comment by sudeep9** [comment]
I tried the `func TestReadMapKeyZC(t *testing.T)` and it does fail with the same reason:

```bash
--- FAIL: TestReadMapKeyZC (0.00s)
    a_test.go:13: msgp: too few bytes left to read object
```

**Comment by erikdubbelboer** [comment]
You are right I made a stupid mistake. I made a pull request now: https://github.com/tinylib/msgp/pull/244
