### ISSUE TITLE
Equivalent to json.RawMessage?

### ISSUE THREAD

**Issue by tisba** [tinylib/msgp#246]
I'm trying to figure out how to achieve the following and I think something like json.RawMessage to delay decoding is what could be useful for this.

I have a very long stream of msgpack messages (100k+). Each message is a array with 2 elements. The first one is a small string "key". The second is the "payload", a large, nested map. I'd like have a efficient way to scan through all messages, to some matching on the first element and only in certain cases decode the second part for further processing. In case the second element is not needed, I would like skip decoding and simply "seek" to the next message.

I hope my description makes sense :) How would I build something like this using this package? With the json package I can use RawMessage to delay the decoding of the payload. But JSON is horribly inefficient for the payload I want to store.

**Comment by philhofer** [comment]
I think you're looking for `msgp.Raw`, which works more-or-less
identically to `json.RawMessage`. Keep in mind, though, that both of
those constructs still need to lex the payload they contain in order
to determine its boundaries in the byte stream, so there's still some
(not much) overhead to skipping large sections of the stream.

**Comment by tisba** [comment]
Thank you, I overlooked `msgp.Raw` somehow :(

I think I need to do some more benchmarks and assessments on how likely it is to skip an entry. Maybe there is another angle to optimise this further.
