### ISSUE TITLE
Decode replaces empty slices with nil

### ISSUE THREAD

**Issue by knadh** [tinylib/msgp#247]
@philhofer @erikdubbelboer https://github.com/tinylib/msgp/issues/219 exists in the case of empty slices, where unmarshalling 0-len slices turn them into `nil`s. Could this behaviour be fixed to be consistent with that of maps?

```go
package main

import (
	"fmt"
)

//go:generate msgp

type Test struct {
	Slice []string          `msg:"slice`
	Map   map[string]string `msg:"map"`
}

var b1, b2 []byte

func main() {
	// Slice and Maps are initialized (non-nil) but have empty values.
	pre := Test{Slice: []string{}, Map: map[string]string{}}
	fmt.Println("pre |", ".Slice == nil ?", pre.Slice == nil, "| .Map == nil ?", pre.Map == nil)

	var (
		b, _ = pre.MarshalMsg(nil)
		post = Test{}
	)
	post.UnmarshalMsg(b)

	// .Slice and has become nil.
	fmt.Println("post |", ".Slice == nil ?", post.Slice == nil, "| .Map == nil ?", post.Map == nil)
}
```

Output:
```
pre | .Slice == nil ? false | .Map == nil ? false
post | .Slice == nil ? true | .Map == nil ? false
```

**Comment by noseglid** [comment]
This is really unexpected behaviour!

Is this intentional, or a bug?

**Comment by erikdubbelboer** [comment]
See: https://github.com/tinylib/msgp/pull/278

**Comment by noseglid** [comment]
Awesome thanks!

I didn't manage to get the actual binary to test re-generate my files. But for the slice that was set to nil, I manually edited the Unmarshal code to be identical to what your changes would do and it works just as I'd expect.

Great work!
