### ISSUE TITLE
Go vet errors on autogenerated tests for structs with sync.Mutex field

### ISSUE THREAD

**Issue by shawnps-sigsci** [tinylib/msgp#255]
Hi, I have a struct with a sync.Mutex field like so:

```
type Foo struct {
  lock sync.Mutex
}
```

and when `msgp` generates test code for this struct, it calls `t.Logf`:

```
v := Foo{}
var buf bytes.Buffer
msgp.Encode(&buf, &v) 
m := v.Msgsize()
if buf.Len() > m { 
        t.Logf("WARNING: Msgsize() for %v is inaccurate", v)
}  
```

But `go vet` gives us an error because of this:

`call of t.Logf copies lock value`

Could this be fixed in `testgen.go` by doing something like this instead?

```
template.Must(encodeTestTempl.Parse(`func TestEncodeDecode{{.TypeName}}(t *testing.T) {
v := {{.TypeName}}{}
var buf bytes.Buffer
msgp.Encode(&buf, &v) 

m := v.Msgsize()
if buf.Len() > m { 
        t.Log("WARNING: TestEncodeDecode{{.TypeName}} Msgsize() is inaccurate")
}   
```

Happy to make a pull request if you're on board with this proposal.

**Comment by philhofer** [comment]
Yep, I'd be happy to accept that PR.

**Comment by shawnps-sigsci** [comment]
Thank you @philhofer. I've created the PR here:

https://github.com/tinylib/msgp/pull/256

I've tested it out locally and it fixes the `go vet` copylocks error for me.
