### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by arl** [tinylib/msgp#258]

**Comment by philhofer** [comment]
I fix reported bugs and merge bugfixes, stability improvements, and documentation improvements. I merged a minor bugfix yesterday.

I'm not actively working on new features.

Commercial support is also available through my business.

**Comment by arl** [comment]
Ok very glad to hear that. I'm asking because we are planning to use msgp
at my company.
Great project by the way, after benchmarking various serialisation libs
that was by far the most performant and easiest to use.
