### ISSUE TITLE
omitempty support

### ISSUE THREAD

**Issue by bradleypeabody** [tinylib/msgp#263]
I want to check if support for "omitempty" can be reconsidered. I've looked through the earlier discussion on this, e.g. https://github.com/tinylib/msgp/issues/103#issuecomment-122414776

Specifically:

> For each of the five methods that we generate today, we would have to make substantial changes. Additionally, many optimizations (constant propagation and pre-serialization in particular) depend on knowing statically the number of elements to be encoded. For some users, the performance penalty may be acceptable, but we would have to make sure people understood the tradeoffs that they were making.

These points make sense. (Although I think it's only the methods related to writing, not reading, no?)  I think it would still make sense to implement as a feature. 

It seems to me the primary difference is whether one is **optimizing for size or encoding speed**.  In my situation, I have a complex series of structs with a lot of fields describing the state of an IoT device, but in many cases a lot of fields are empty.  These then end up msgpack'ed in a database field and read many times.  Compacting this information to reduce data size read/written to/from disk and transferred over the network is much more important for performance here than initial encoding speed.  The only immediate solution I see right now is to implement EncodeMsg by hand.

That said, how about the following for "omitempty" support:

* Existing generated code for EncodeMsg and MarshalMsg is exactly the same.
* Adding `msg:"myfield,omitempty"` on one or more struct fields triggers the additional logic of checking for empty field values before writing the map header.
* And of course the `if` statements that go around each field for empty check.
* Then this fact is just documented, e.g. "Using 'omitempty' on any field emits additional code to check for empty values and can reduce write performance in favor of producing smaller output.  (Performance implications of course depend on your use case, but see here for a benchmark ... ~X% is a sensible estimate.)".

Does that seem workable?  I don't really see a down side as all of the existing gains from what you have remain intact, it just allows this tradeoff if size reduction is more important.  If you can point me in the right direction of where to make these changes I'll see if I can get in there and make a prototype, get together a PR and we can discuss what would be needed to merge.

**Comment by philhofer** [comment]
As long as you've got a sense of where the sharp edges are in this
feature, feel free to take a crack at it.

**Comment by bradleypeabody** [comment]
As a note regarding https://github.com/tinylib/msgp/pull/164#issuecomment-254035661 and "omitempty" on decode, I think it will work to collect up which fields have been decoded from the map into a bitmask and then for any that were missing set them to zero value.  Seems very doable.  I also think "omitemptyenc" and "omitemptydec" could also be used to only specify the behavior upon encode (and marshal) and/or decode (and unmarshal); with "omitempty" meaning both behaviors enabled.

I believe this would address these concerns.

**Comment by philhofer** [comment]
Yeah, that sounds workable.

**Comment by bradleypeabody** [comment]
I have the basic functionality working for this feature. This diff covers the relevant changes: https://github.com/bradleypeabody/msgp/commit/7a06e284357bcfefe778df8879cafe0862c56156
(the first part is the tests, but for example here is encodeGen.structmap: https://github.com/bradleypeabody/msgp/commit/7a06e284357bcfefe778df8879cafe0862c56156#diff-dd3f24708b6c649ad70a4ce4057a5973L112 )

I would like to get any initial feedback to ensure this is generally on track, and if not, what the concerns are or what needs to be fixed.

The highlights are:

- If you **don't specify `omitempty`** (or omitemptyenc or emptyemptydec - those are implemented as described above), the output should be exactly the same as it has been.  So this **doesn't break or change anything for existing users** of the library.
- The two relevant encoding methods `encodeGen.structmap()` and `marshalGen.mapstruct()` now have a block at the top to check for omitempty and examine each relevant field for emptiness, and then an if statement that is activated if needed for each specific field.
- A **bitmask** of the appropriate size **is used to keep track of which fields are empty/missing**.  This seemed most efficient both for space and speed.  It expands to be an array of uint64 if there are more than 64 struct fields.
- The two relevant decoding methods `decodeGen.structAsMap()` and `unmarshalGen) mapstruct()` do the inverse, and when decoding keep track of which fields were found, and then if tagged, zero out the fields not found in the map. (Now that I think of it, **maybe there should be just two options - "omitempty" and "emptymissing"** - that would make it so "omitempty" has the same semantics as encoding/json - let me know if any thoughts on that)
- Most of the relevant code has been put in **gen/oempty.go** - I'm not sure if it's entirely consistent with the rest of the code base, but it seemed sensible to group as much of this logic as possible into one file rather than having it be too scattered throughout the code base.
- **I had to add StructField.FieldTagParts** to make omitempty/omitemptyenc/omitemptydec available during code generation, let me know if you want this done a different way (such as parsing it earlier and adding bools for each of these options to StructField instead)
- In some places I've been **less stringent about performance in the code generation implementation** itself (some more string formatting and copying that could potentially be optimized out if that's important enough), **but the generated code ought to be blazing fast** - I did every optimization I could think of and tried to keep it as simple as possible.
- There are also **no dependency changes** - no 3rd party libraries introduced, no imports added to the generated code.  And **no methods added to the generated code**.

Generated EncodeMsg looks like:

```
// EncodeMsg implements msgp.Encodable
func (z *SomeTest) EncodeMsg(en *msgp.Writer) (err error) {
	// omitempty: check for empty values
	zFieldN := 4
	var zEmptyMask uint8

	if len(z.Field00) == 0 {
		zFieldN--
		zEmptyMask |= 0x1
	}

	// ...

	// dynamic map header, size zFieldN
	err = en.Append(0x80 | (uint8(zFieldN) & 0x0F))

	// ...
	
	if (zEmptyMask & 0x1) == 0 { // if not empty
		// ... all the same stuff here
		err = en.Append(0xa7, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x30, 0x30)
		err = en.WriteString(z.Field00)
	}

	// ... all the same stuff here (if no omitempty check for this field there's no if statement,
	// exactly the same)
	err = en.Append(0xa7, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x30, 0x31)

	// ...

	return
}
```

Generated DecodeMsg is more or less the inverse.

Marshal and Unmarshal are very similar.

Left to be done (aside from any cleanup and feedback) is to go through the various scenarios and ensure everything works for cases like `type Whatever string`, embedded structs, flattened structs, anonymous structs, etc., writing tests for this and fixing as I go.  The trickiest part left is figuring out what exact "zero value" to use for each field type. However I'm fairly confident at this point that I'll be able to support most of these and the ones that cannot realistically be supported will just revert the the old behavior.  I should have this all together some time next week.

Feedback welcome.  I'd definitely like to do whatever is necessary so this is a mergeable feature.

**Comment by philhofer** [comment]
Great, thanks for your hard work on this.

I'm on board with your overall strategy.

I made some line-by-line comments, and I'll have some time later today
to make a few more.

Re. "zero value" behavior, on the encoding side, I think we should try
to emulate encoding/json unless there's a pressing reason not to.

**Comment by bradleypeabody** [comment]
Awesome!

To recap/summarize:

- bmask as a type sounds great, will do
- will merge isOmitEmpty as you mentioned
- removing gotos (just accidentally left over from an earlier attempt)
- I will move zero expression stuff onto Elem
- I will go ahead and remove omitemptyGen as a type and just change any methods not otherwise moved to be regular functions
- understood and agreed on the behavior of "omitempty" (from the [docs](https://golang.org/pkg/encoding/json/#Marshal): *The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.* - I think we should also support structs, I'm not really sure why they didn't)
- unless you have an objection, I'll also make it so "omitempty" only affects encoding, and "emptyomitted" is a separate option for decoding
- And I'll get the rest of the scenarios of different types put into tests and that all ironed out (everything either working or at least correctly falling back to the prior behavior).
- I'll also see if I can put together a couple paragraphs or so that succinctly describe the functionality, which can be used to update the documentation.

I'll need a few days but I hope be able to get all this turned back around soon (mid-week or so).

**Comment by bradleypeabody** [comment]
I keep going back and forth on the struct tag option names.  After a bit more thought, I'm leaning toward:

- "omitempty" - affects encoding, same as encoding/json
- "fillempty" - the inverse filling upon decode
- "autoempty" - same as "omitempty,fillempty"

I think these are more concise, more consistent and read better.

**Comment by philhofer** [comment]
If you'd like, you can punt on the decode side of this change and we
can do only the encoding side. I'm not 100% sure what the decode side
should look like either.

Practically speaking, if you want absent fields zeroed in decoding,
you can just re-initialize your struct to the zero value before
decoding, which would likely be faster than just touching individual
fields anyway.

**Comment by bradleypeabody** [comment]
That is an interesting point I had not considered.  I agree, just the encoding for now.

**Comment by bradleypeabody** [comment]
I'm having second thoughts about leaving the decode step unchanged, here's why:

```go
type Item struct {
    Name []byte `msg:"n,omitempty"`
    SubItemlist []SubItem `msg:"l,omitempty"`
}
type SubItem struct {
    Prop1 uint64 `msg:"p,omitempty"`
}
```

For the emitted code that does slice decode, the (correct and appropriate) re-use idiom is employed `if cap(x) >= n { x = x[:n] } else { x = make(...) }`.  This is normally a good thing, except that with omitempty, decoding into an instance of `Item` multiple times can result in both `Name` and `SubItemList` not being set and instead left as the prior value.  And in the case of a slice of structs - some SubItem instances here can end up being re-used with the `x = x[:n]` above and if Prop1 was empty before, you'll need up with the prior value.

I think the situation we have now is that one *must* zero the struct before decoding in order to ensure correct behavior, and this of course loses the gains of being able to re-use slices to avoid unnecessary allocation.

I believe the following changes would address these issues:

- **For slices (and probably maps too), "empty" should be defined as len(x)==0, rather than nil.**  This is different from encoding/json, but I believe it is an appropriate change based on the performance focus of this library.  This allow us to re-use slices and avoid allocations, an appropriate behavior in this case.  If one does not want this (i.e. some of the deep data is, after some additional processing by the user, now being pointed to by other parts of the program), zeroing out the top level item before decoding disables the behavior.
- **The "if field not present, set it to zero" behavior should be available via a separate option.**  This would cause slices that were omitted from the original encode (either from omitempty or from a prior version) to be explicitly set to zero while still allowing the slice re-use to work properly and avoid extra allocations.  "Setting a slice to zero" would mean `x := x[:0]` (not `x = nil`).

Any objection to these changes?  It's not very much work to implement the above from where the PR is now, and I think very worth it in terms of producing expected behavior for users.

**Comment by philhofer** [comment]
It has never been correct to re-use structures for decoding without
re-initializing them to a sane default value, since fields could
always be omitted by some other implementation.

Right now "empty" means "the Go zero value," which is a simple and consistent
definition that we can apply everywhere. I think it would violate the
principle of least
surprise to do something else, particularly since the impetus for the
implementation
comes straight from the standard library.

If you really need to re-use slice fields, you can work around the
field being cleared
by caching the slices elsewhere. It's not ideal, but I also don't get
the sense that it's
a common use case. (I'd be happy to be proved wrong!)

Re. "if the field is not present, set it to zero," I'm happy to
entertain a separate PR for
that feature if it's justified by benchmarks. But my intuition is that
a) zeroing and
re-initializing values is trivial overhead relative to overall
decoding, and b) bulk zeroing
beats additional per-field logic in most practical cases.
