### ISSUE TITLE
errWrapped should have an Unwrap method

### ISSUE THREAD

**Issue by bradleypeabody** [tinylib/msgp#269]
The latest changes to https://golang.org/pkg/errors/ provide for an error wrapping mechanism in the Go standard library.  Things should work as expected with `errors.Is()` and other such methods if an `Unwrap() error` method is added to errWrap (see https://github.com/tinylib/msgp/blob/master/msgp/errors.go#L106 ).

Let me know if you agree and I can make a PR for it.

**Comment by philhofer** [comment]
Yes! Sounds good.
