### ISSUE TITLE
feature request: ability to filter separate files/structs in a single directory

### ISSUE THREAD

**Issue by agnivade** [tinylib/msgp#274]
Hello,

I am investigating this package, and I came across a limitation which is preventing me from using this. I have a directory which is a superset of all the structs that I would ever need to marshal/unmarshal.

The problem is that if I generate the code on the entire directory, it fails on a lot of structs which have other structs or things like xml.Name/time.Duration. The thing is that I don't even want those structs to be serialized, so there is no need to generate code for that. And unfortunately I can't ignore those too because it's a compiler error.

I am wondering if it makes sense to add the ability to select separate files/structs in a single directory ? That way I can add some special magic comment on my structs and get on with it.

Even if I run the `msgp` command multiple times on several files, it won't work because each struct has other dependencies in other files in the same directory. So there has to be a way to pass multiple files in a single shot which would scan all the structs in them along with their dependencies.

Thanks.

**Comment by philhofer** [comment]
Not sure I understand the problem. Can't you just put the
`//go:generate` directive in the files that need code generated?

**Comment by philhofer** [comment]
(And the `//msgp:ignore` directive will let you ignore particular type
declarations in those files.)

**Comment by agnivade** [comment]
Ah yes, the ignore directive was what I was looking for. Thanks. :) Was that documented somewhere and I missed it ?

**Comment by agnivade** [comment]
Hmm .. does it not work with struct fields which are in different files?

I have a struct field which is another struct and is in a different file. I placed the `//go: generate` directive in both files. But I still get an `unresolved identifier` warning. But when I place the struct in the same file, I don't get an error anymore.

Wondering if I am missing something?

**Comment by philhofer** [comment]
The tool is file-based (for historical reasons, but also because the
go/loader and go/ast packages have asymptotically terrible performance
on really large codebases).
