### ISSUE TITLE
complex64 -- took me a while to work out how to use this

### ISSUE THREAD

**Issue by DazWilkin** [tinylib/msgp#277]
Nice library! Thank you.

The documentation describes [Extension Types](https://github.com/tinylib/msgp/wiki/Using-Extensions) and that e.g. `complex64` (and other) Golang native types are supported, but without an example.

I assumed (incorrectly):

```golang
type Request struct {
    A complex64 `msg:"a,extension"`
    ...
```

But was unsure how this in-built type would have e.g. `ExtensionType()` method.

I, of course, received errors:

```console
cannot use &z.A (type *complex64) as type msgp.Extension in argument to dc.ReadExtension:
	*complex64 does not implement msgp.Extension (missing ExtensionType method)
```

I was unable to find the implementation of the interface (looked for e.g. `ExtensionType()` methods).

Eventually, I stumbled upon the solution:

```golang
type Request struct {
    A complex64 `msg:"a,complex"`
    ...
```

Recommend: include a simple example using one of the complex or Time types how to use them.

**Comment by klauspost** [comment]
Nothing special required, you just do `A complex64 `msg:"a"`.

Feel free to add to the wiki.
