### ISSUE TITLE
Compilation error about unused variable in generated *_gen.go file if the struct only has a single property

### ISSUE THREAD

**Issue by dsidirop** [tinylib/msgp#306]
Running msgp ver. 1.1.6 (latest at the time of this writing) with golang ver. 1.17.7 linux/amd64.

Got this simple struct:

        package arena
        
        type VitalsTemplate struct {
        	Spec VitalsTemplateSpec `                        json:"spec,omitempty"                       msg:"spec,omitempty"                     bson:"spec,omitempty"                      `
        	Foo  *int               `                        json:"foo,omitempty"                        msg:"foo,omitempty"                      bson:"foo,omitempty"                       ` //stupid hack to dodge stupid msgp error
        }
        
        type VitalsTemplateSpec struct {
        	RespiratoryRate *int64 `       json:"respiratory_rate,omitempty"           msg:"respiratory_rate,omitempty"         bson:"respiratory_rate,omitempty"          `
        	SpO2            *int64 `       json:"spo2,omitempty"                       msg:"spo2,omitempty"                     bson:"spo2,omitempty"                      `
        }

Running 'msgp   --file   vitalstemplate.go'  generates a proper 'vitalstemplate_gen.go' without errors.

However if the 'Foo' property gets removed then 'vitalstemplate_gen.go' contains unused variables which causes the compilation to fail:

         // EncodeMsg implements msgp.Encodable
         func (z *VitalsTemplate) EncodeMsg(en *msgp.Writer) (err error) {
         	// omitempty: check for empty values
         	zb0001Len := uint32(1)
         	var zb0001Mask uint8 /* 1 bits */    <----- unused!
         	// variable map header, size zb0001Len
         	err = en.Append(0x80 | uint8(zb0001Len))
         	if err != nil {
         		return
         	}
         	if zb0001Len == 0 {
         		return
         	}

        // EncodeMsg implements msgp.Encodable
        func (z *VitalsTemplate) EncodeMsg(en *msgp.Writer) (err error) {
        	// omitempty: check for empty values
        	zb0001Len := uint32(1)
        	var zb0001Mask uint8 /* 1 bits */  <----- unused
        	// variable map header, size zb0001Len
        	err = en.Append(0x80 | uint8(zb0001Len))
        	if err != nil {
        		return
        	}
        	if zb0001Len == 0 {
        		return
        	}

**Comment by klauspost** [comment]
Output code is now:

```
// EncodeMsg implements msgp.Encodable
func (z *VitalsTemplate) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(1)
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}
	if zb0001Len == 0 {
		return
	}
	// write "spec"
	err = en.Append(0xa4, 0x73, 0x70, 0x65, 0x63)
	if err != nil {
		return
	}
	err = z.Spec.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Spec")
		return
	}
	return
}
```
