### ISSUE TITLE
unnecessary wrapping

### ISSUE THREAD

**Issue by artvel** [tinylib/msgp#308]
Having a structure like:
```
type A struct {
 Field1 int
 Field2 string
}
type B struct {
 A
}
```

Produces currently an unnecessary wrapped outcome:
```
B.A.Field1
B.A.Field2
```

Expected outcome:
```
B.Field1
B.Field2
```

**Comment by photoszzt** [comment]
there's a flatten tag which implements this behavior. 

type B struct {
  A `msg",flatten"
}

But it seems it only works if A and B is in the same file. This breaks if it's in a different file. Worse, it doesn't print any warning that it skips a field during generation.

**Comment by klauspost** [comment]
Is there any actual problems arising from this?
