### ISSUE TITLE
new cmd option to generate 1 file per package

### ISSUE THREAD

**Issue by artvel** [tinylib/msgp#309]
Having multiple generated files is not adding any benefits.

**Implement a way to have one file per package to prevent from annoying deletions wehn maintaining. 
This means in total there will be 2 files generated if tests were requested.**

**Comment by klauspost** [comment]
First, I disagree on the premise. Having a 1:1 relation with your input files makes it very easy to locate relevant code and keeps generated files at a reasonable size.

Second, msgp is operating purely on a per-file basis and this directly conflicts with that.
