### ISSUE TITLE
Add Linux and Windows binaries into the release section

### ISSUE THREAD

**Issue by yusufozturk** [tinylib/msgp#314]
Thanks for this library. Benchmarks looks amazing.

But I had trouble to start using library. In my case, I wasn't able to install library to do code generation (maybe a change in go 1.19?).

I was getting:
running "msgp": exec: "msgp": executable file not found in $PATH

So I had to fork this library and build the files. If someone needs them, here they are.

[msgp.zip](https://github.com/tinylib/msgp/files/9450466/msgp.zip)

In the zip file, you can find Windows and Linux binaries.

I think they should be in the release section, so people can download them directly. This will resolve the issue with $PATH.

**How to use it?**

Just copy the binary to the path, where you go file is. And then run:

`msgp.exe -file dashboard.go`

This will generate the files.

PS: Just a feedback. Project landing page is not very clear. I was going crazy to find wiki :) I think landing page can be more clear to show how to use this library instead of just talking about all other stuff.

**Comment by RichieSams** [comment]
You can just do `go install github.com/tinylib/msgp@latest`

That will compile the binary and put it in your GOROOT/bin folder. Assuming that is on your PATH, then you're good to go

**Comment by klauspost** [comment]
Yeah. This is for Go development, so using the command above seems like the most reasonable.
