### ISSUE TITLE
"no definitions in issue185_test.go"

### ISSUE THREAD

**Issue by gibmat** [tinylib/msgp#317]
I'm working on updating the ancient version of this library in Debian (1.0.2) to the current release (1.1.6). However, when refreshing the generated code during the build I encounter this error:
```
src/github.com/tinylib/msgp/issue185_test.go
no definitions in issue185_test.go
src/github.com/tinylib/msgp/issue185_test.go:246: running "msgp": exit status 1
```
I'm not familiar with the workings of this library, so I don't know if this error is specific to something in Debian's build environment, or if this is an actual issue.

**Comment by klauspost** [comment]
Closing as this file no longer exists.
