### ISSUE TITLE
Add generator option to always produce pointer receivers

### ISSUE THREAD

**Issue by mjmar01** [tinylib/msgp#332]
I'd like to propose a command line parameter for the generator like "receiver-preference" or similar to modify the [receiver logic](https://github.com/tinylib/msgp/blob/6ac204f0b4d48d17ab4fa442134c7fba13127a4e/gen/spec.go#L255) for Marshal and MsgSize methods. So it could either do:

- Pointer receivers for everything
- Pointer receivers for unmarshal methods, but non-pointer receivers for marshal methods (this might also satisfy a previous [issue](https://github.com/tinylib/msgp/issues/155))
- Dynamic like before

Currently the generator will frequently mix receiver types for generated methods. This causes annoyances in some scenarios like for example when using both the Unmarshaler and Marshaler interfaces in another custom interface. Since generated types often don't implement both of these interfaces at once, the custom interface might also become unusable.

Currently you could work around this by including unexported and omitted fields in the struct to fool the generator into using pointer receivers:
```
//go:generate msgp -unexported

type MyCustomType struct {
	forcePtrRcvr     struct{}    `msg:"_,omitempty"`
	ArbitraryField   int
}
```
But this is unclean and doesn't work when encoding to tuples using `//msgp:tuple MyCustomType`, when using basic types (not structs) or when unexported fields should not be serialized at all.

Let me know what you think and if I can provide further information or assistance :)

**Comment by klauspost** [comment]
If implemented as directives, I for sure wouldn't mind it. Keeping the commandline "clean" is IMO better design.

To me the cleanest would be:

```
//msgp:pointer
```

... simply as a file level directive.

**Comment by klauspost** [comment]
```
type NamedBool    bool
```

Will need some special care, as forcing pointers on these means the code will also need to change.

Also we maybe have to deal with the fact that the receiver can now be nil.

**Comment by klauspost** [comment]
See #357
