### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by klauspost** [tinylib/msgp#354]
@philhofer Looking at the change log there are some nice new features. 

Unless you have objections I think we should release a v1.2.0 since this seems like more than a "bugfix release".

(feel free to do so, otherwise just give it 👍🏼 or 👎🏼 and I will release it tomorrow)

**Comment by philhofer** [comment]
Sounds good!

**Comment by klauspost** [comment]
👍🏼 Released.
