### ISSUE TITLE
bad link on wiki page https://github.com/tinylib/msgp/wiki/Using-the-Code-Generator

### ISSUE THREAD

**Issue by client9** [tinylib/msgp#51]
thanks for your hard work.. 

I found a 404 on a doco page..

at the bottom of  https://github.com/tinylib/msgp/wiki/Using-the-Code-Generator there is a link to 

Godoc

which goes here:

http://godoc.org/github.com/philhofer/msgp/msgp

404

**Comment by philhofer** [comment]
Fixed! Thanks.
