### ISSUE TITLE
Issues with fixed size arrays

### ISSUE THREAD

**Issue by ebfe** [tinylib/msgp#55]
The generated code for fixed-size byte arrays fails to compile. For example:

    $ cat types.go
    //go:generate msgp -file types.go 
    
    package foo 
    
    type X struct {
            Items [32]byte `msg:"items"`
    }
    $ go generate
    [...]
    $ go build
    [...]
    ./types_gen.go:62: dc.ReadByte undefined (type *msgp.Reader has no field or method ReadByte)
    ./types_gen.go:133: undefined: msgp.ByteSize

While this error seems to be specific to `byte` and the generated code for
other types compiles, the generated test-suite fails for at least `string` and the `int` variants. For example:

    $ cat types.go
    package foo 
    
    //go:generate msgp -file types.go 
    
    type X struct {
            Items [32]int32 `msg:"items"`
    }
    $ go generate
    [...]
    $ go test
    --- FAIL: TestXMarshalUnmarshal (0.00s)
            types_gen_test.go:87: 1 bytes left over after Skip(): "\x00"
    FAIL
    exit status 1
    [...]

**Comment by philhofer** [comment]
I found the issue. (In case you're interested, it was this guy here: https://github.com/tinylib/msgp/compare/hfix-array?expand=1#diff-a396487011780c1b0db41b95f751cf0eR36).

Should be fixed in a second.

**Comment by philhofer** [comment]
Thanks for the issue report, btw!

**Comment by ebfe** [comment]
Thanks for fixing this so quickly.
