### ISSUE TITLE
Unused variable error in Msgsize() for structs containing a slice of arrays

### ISSUE THREAD

**Issue by ebfe** [tinylib/msgp#58]
```Go
//go:generate msgp -file types.go 

package foo 

type X struct {
	Items [][32]int`msg:"items"`
}
```

The generated code fails to compile due to an unused variable in Msgsize():

```
./types_gen.go:167: xvk declared and not used
```

```
   165  func (z *X) Msgsize() (s int) {
   166          s = msgp.MapHeaderSize + msgp.StringPrefixSize + 5 + msgp.ArrayHeaderSize
   167          for xvk := range z.Items {
   168                  s += msgp.ArrayHeaderSize + (32 * (msgp.IntSize))
   169          }
   170          return
   171  }
```

Line 167 should probably read `for _ = range z.Items` or (similar as it is
done in sizeGen.gMap) `_ = xvk` added to the loop body. Something like 04c66628de53 would
fix this, but introduces a lot of unnecessary `_ = idx` statements.

**Comment by philhofer** [comment]
I came up with a solution ( #59 ) that will always avoid the `range` in favor of an expression like `len(a) * size`. The unused variable was basically an indication that the size computation was doing something sub-optimal, so I managed to kill two birds with one stone by optimizing a bit. (Now `(*X).Msgsize()` is one line, as it should be.)
