### ISSUE TITLE
Shims generate functions with the shimmed type as receiver

### ISSUE THREAD

**Issue by zond** [tinylib/msgp#65]
In #31 a nice functionality was implemented to generate shims for generic types.

Unfortunately, when I run the code now, it seems the generator generates functions with the shimmed type as receiver.

The entire point of the shim (for me, at least) was to be able to encode third party types that I can't create new functions for.

Example:

```
//go:generate msgp
//msgp:shim datastore.Key as:string using:utils.EncodeKey/utils.DecodeKey
package user

import "appengine/datastore"

type User struct {
  Id *datastore.Key
  Name string
}
```

When I run `go generate` with this code, something like 

```
// MarshalMsg implements msgp.Marshaler
func (z *datastore.Key) MarshalMsg(b []byte) (o []byte, err error) {
        o = msgp.Require(b, z.Msgsize())
        o = msgp.AppendString(o, common.EncodeKey((*z)))
        return
}
```

will be generated, but won't compile of course.

**Comment by philhofer** [comment]
Good catch. I overhauled the code generator a little while ago, and it appears this particular case never made it into the test suite. Apologies. (The way the generator behaves now is by generating code for every type separately, and then inlining the definitions into one another.)

I'll add a rule that prevents generating methods for type names with selectors in them.

**Comment by philhofer** [comment]
WIP is on #66 .

I did make one small tweak: you can now shim pointer types. So, if you write your shim directive as:
```go
//msgp:shim datastore.Key as:string using:utils.EncodeKey/utils.DecodeKey
```
... and EncodeKey/DecodeKey take pointers, you can prevent passing (rather large) structs by value.

**Comment by zond** [comment]
Thanks, I'll try it now :)
