### ISSUE TITLE
Use build tags or similar to enable using msgp without using unsafe package

### ISSUE THREAD

**Issue by zond** [tinylib/msgp#68]
App Engine doesn't allow importing unsafe, so right now it's impossible to use this lib there :/

**Comment by philhofer** [comment]
I agree that it would be nice to support appengine. However, that means someone is going to have to go through and replace all the bitcasts with something much more verbose. (That is, unless appengine allows unsafe code in the standard library, in which case it might be easier.)

**Comment by zond** [comment]
App Engine does allow unsafe inside the standard library.

But my idea (if no stdlib solution exists) was to have a function pointer that does the bit casts, and let a build tag controlled file set it to either safe or unsafe. I haven't looked at the code though, so it might not be that simple..

**Comment by philhofer** [comment]
The places that would need to be appengine-specific are:
 - The implementation of `Number` (add a `float64` field for the appengine build, and then store floats in threre.)
 - The (trivial) implementations of `UnsafeString` and `UnsafeBytes` (to `string()` and `[]byte()`)

There will undoubtedly be a performance regression (particularly for decoding/unmarshaling), but some of that will be improved by better escape analysis in go1.5.

I'll take a look at this in a day or two, but I'm more than happy to review PRs.

**Comment by philhofer** [comment]
@zond - Give https://github.com/tinylib/msgp/tree/appengine a try an let me know how it goes.

**Comment by zond** [comment]
Damn, my day job keeps taking all my time.

Now I was finally able to try this out again.

Unfortunately github.com/philhofer/fwd uses unsafe, so even after your excellent work with the appengine build tag, it didn't work :/

I'll add a similar issue to the fwd package, and see if philhofer is as helpful.

**Comment by zond** [comment]
Hey, you are philhofer!

Derp.

I'll just add a bug there, and reference this one :D
