### ISSUE TITLE
Make the encode funcs bound to the types, not pointers the types.

### ISSUE THREAD

**Issue by zond** [tinylib/msgp#71]
Because most encoding frameworks allow encoding either values or pointers to values (even if they only allow decoding to pointers for obvious reasons), it would ease integration with msgp if the encoder funcs were bound to values instead of pointers.

As in:

func (t Type) MarshalMsg ...

vs

func (t *Type) MarshalMsg ...

Maybe you have good reasons for having pointer receivers, but since I guess most of any type gets accessed in the encode func anyway, the copy shouldn't (without me having benchmarked this at all :) be slower than doing lots of dereferencing in a pointer receiver func.

Also, the value receiver func will work even when you have a *t, but not the reverse, so it's easier on the user :D 

Does this make sense, or am I missing something?

**Comment by philhofer** [comment]
It probably makes sense to pursue this for types that are 3 machine words or smaller. (In other words, types that people are already passing around by value.) I don't think it makes sense in all cases, though. You're trading `LEA`s for `MOV`s, although not always in equal numbers.

**Comment by zond** [comment]
Or have an option, either when generating or as a //-directive?

**Comment by zond** [comment]
I imagine having a default (bound to pointers like now, or if one wants to be fancy, bound to pointers if the type is larger than 3 words?), and make it possible to hard set it to all-pointers or all-non-pointers via precompiler directives?

**Comment by philhofer** [comment]
That sounds reasonable. The default bit will be easy, but changing the receiver type for one method in particular via directive is going to be tricky, because the directives operate independently of any specific method to be generated.

**Comment by philhofer** [comment]
Detected automatically after #74  and #75.
