### ISSUE TITLE
Type support for complex objects

### ISSUE THREAD

**Issue by Ganitzsh** [tinylib/msgp#81]
Hello.
I'm experiencing a problem while trying to encode a complex object.
The structure is the following:
```go
type MyStructA struct {
  Field interface{}
}

type MyStructB struct {
  Field MyStructC
}

type MyStructC struct {
 Field string
}
```
I need to encode an object of type ``MyStructA`` which contains an object of type ``MyStructB`` containing an object of type ``MyStructC`` :
```go
package main

myObj := MyStructA {
 Field: MyStructB{
  Field: MyStructC{
   Field: "string",
  },
 },
}
```
After I generate the file using ``go generate`` (including this message ``inlining methods for MyStructC into MyStructB``)  and build using ``go build`` successfully with no errors or warning I get the following runtime error:
``msgp: type "main.MyStructB" not supported``
Now, if I change the ``MyStructB`` to this
```go
type MyStructB struct {
 Field string // Changed from MyStructC to primitive type string
}
```
This works. Am I doing it wrong? As I can see in the code, it fails when checking the type of ``Field`` inside ``MyStructB``

**Comment by philhofer** [comment]
Does the error show up in the automated tests?

That error should only show up if you pass a type to `WriteIntf` or `AppendIntf` that isn't either a primitive or an implementor of `Encodable`/`Marshaler`, respectively.

**Comment by philhofer** [comment]
Okay. I was able to reproduce the error. You want `MyStructA.Field` to be `*MyStructB`, not `MyStructB`.

**Comment by Ganitzsh** [comment]
Ok! Now I get it, didn't pay attention to that in the generated code... Thank you very much! It works like a charm.

**Comment by philhofer** [comment]
No problem - glad I could help.
