### ISSUE TITLE
multicore

### ISSUE THREAD

**Issue by vessenes** [tinylib/msgp#83]
We're using msgp a lot lately, and like it. Thank you! 

We are marshalling and unmarshalling 40GB of data every 15-60 minutes, and have been doing a lot of this recently: https://xkcd.com/303/. Speeds are roughly 250MB/s from msgp. Which kicks ass. BUT, our disk storage runs at something like 900MB/S and we have a huge RAM cache which makes me suspect we could get at least a 4x speedup with some extra cores thrown at this. That would be great. 

I've been thinking over whether one could automatically goroutinize a large load, and I'm curious for your thoughts about it. We could reinstrument our marshal/unmarshal functions to split data into files and recombine after load, but it would be really great to shard out reading from slices leaving one file which could be read single threaded or multicore. Any thoughts on doing this?

**Comment by philhofer** [comment]
I'm not sure I understand what you're suggesting, but I have a couple thoughts, in no particular order:

 - If speed is important, and you're processing large files, you could try memory-mapping them. Unmarshaling is more-or-less strictly sequential, so you could also [`madvise`](http://man7.org/linux/man-pages/man2/madvise.2.html) as such. The methods on `[]byte` are much faster than the ones on `io.Reader`, all else being equal; you'll probably see a ~2x improvement there.

 - MessagePack does not contain delimiters that would allow you to easily break up the stream. You would have to traverse the whole stream once to figure out what offsets pointed to complete objects, and then spawn goroutines pointing to different hunks of memory. That would be slower than just using a single core (in most cases), because traversal is only two or three times as fast as unmarshalling. TL;DR raw MessagePack needs to be processed sequentially, and so there is no effective means of parallelization w/o extra information.

Can you give me a more concrete example of the structure of your workload?

**Comment by vessenes** [comment]
Thanks for the thoughts, mmap is a good plan; I hadn't heard of madvise. I'll let you know how this goes.

I was thinking this morning; for arrays and maps, one could include a lower case special instruction, say 
```
    type FastStruct struct {
          BigArray []FancyStruct
          BigMap map[FancyStruct]FancyVal
          shardInto int
    }
```

and then you could prepend each shard's byte offsets into the saved file; if you then wanted to Unmarshal with concurrency, you could spin up as many shard processors as you wanted concurrently. But, as you say, I don't know where in a message pack file that would work; at the very least I imagine you could split BigArray into separate arrays and message pack would not combine them. 

Our data varies, but the slowest load is roughly 70mm structs of the form
```
type SlowStruct struct {
   Index FixedSizeIndex
   DataOne []FixedLengthData
   DataTwo []FixedLengthData2
}
```

**Comment by philhofer** [comment]
One trick you could use for `SlowStruct` is implement `msgp.Extension` and enforce a fixed encoding size. For example:

```go
type SlowStruct struct {
    Index   uint64
    DataOne [16]byte
    DataTwo [16]byte
}

func (s *SlowStruct) MarshalBinaryTo(b []byte) error {
    copy(b, *(*[8]byte)(unsafe.Pointer(&s.Index))[:])
    copy(b[8:], s.DataOne)
    copy(b[24:], s.DataTwo)
    return nil 
}

func (s *SlowStruct) Len() int { return 40 }
```

Then, you'd save your file as a `[]SlowStruct`. Once you read the size of the array, you could then split the following `[]byte` into chunks that were multiples of 40 bytes, and read each of those chunks on separate cores.

**Comment by vessenes** [comment]
The issue in my case is that the number of DataOnes and DataTwos varies from 0 to 10,000 or so for any given item. I think your solution only works if I have a reasonable fixed max size for my DataOne/Two array. Do you agree?

**Comment by philhofer** [comment]
Ah. Then what you need to do is implement `msgp.Extension` for `FixedLengthData` (or otherwise guarantee its wire size). Then you can implement `msgp.Extension` for `[]FixedLengthData` using goroutines.

Something like the following (error handling elided)
```go
const DataOneSize = 128
const procs = 8 

//msgp:ignore DataGroup
type DataGroup []DataOne

func (*d DataGroup) UnmarshalBinary(b []byte) error {
    n, b, _ := msgp.ReadArrayHeader(b)
    chunkSize := n/procs // number of elements for each goroutine

    if cap(*d) < n {
        *d = make([]DataGroup, n)
    } else {
        *d = (*d)[:n]
    }

    var wg sync.WaitGroup
    for i:=0; i<procs; i++ {
        go func(d *DataGroup, i int, chunkSize uint32, wg *sync.WaitGroup, data []byte) {
            start := i * chunkSize
            end := start + chunkSize
            byteIdx := start * DataOneSize
            for i := range (*d)[start:end] {
                d[i].UnmarshalBinary(data[byteIdx:])
                byteIdx += DataOneSize
            }
            wg.Done()
        }(d, i, chunkSize, wg, b)
    }
    wg.Wait()
    return nil
}

**Comment by philhofer** [comment]
P.S. I couldn't help but notice that you're in Seattle. We could always discuss this in person.

**Comment by vessenes** [comment]
Interesting idea.. I wouldn't normally put my goroutine spawning so far down, since this will result in roughly 140mm goroutines being launched and a LOT of sync.Mutex hits.. But I'm helped to see how we'd implement this with your library, thank you.

As a side note, this is the sort of thing I'd love to see more in go libraries; what you wrote is generally applicable to many situations, and probably a win for most work done in go.

I'm going to split my data out into separate files and parse them in sequence. I'll follow up with results here.

Yeah, I'll drop you a line on e-mail re: coffee, always happy to meet new Gophers.

**Comment by vessenes** [comment]
Just to follow up, splitting into smaller msgpack files was a big win for us; down from total load time (of all pieces, not just msgpack) of 8 minutes to 2:50 or so. It would be rad to have that option as part of the library, but I can understand why you might now want to.

**Comment by philhofer** [comment]
@vessenes You should check out #98. It doesn't do splitting for you, but it does read/write large files real quickly.

**Comment by vessenes** [comment]
Good idea; we'll check it out. Thanks!

**Comment by klauspost** [comment]
9 years later, I don't see this happening. There are no split points and msgp cannot forward since it is a strictly serial format. Closing until a concrete plan for implementation can be made.
