### ISSUE TITLE
Process unexported types

### ISSUE THREAD

**Issue by ebfe** [tinylib/msgp#93]
At the moment msgp  seems to ignore unexported types and does not generate any code for them.
More often than not, I just want to parse some msgpack data and not export the type parsed into. Is there a reason why msgp ignores unexported types?

Dropping the `ast.FileExports` calls in `parse/getast.go` enables processing of unexported types and so far I haven't hit any ill effects.

**Comment by philhofer** [comment]
This is by design. The standard library does it this way, so I wanted to preserve that behavior for the sake of consistency.

That being said, I think it would be worthwhile to have an option to change this behavior. But I'd like the default behavior to remain as it is.

**Comment by ttacon** [comment]
I agree completely - I would also like this feature :)

**Comment by ebfe** [comment]
Fixed with #95
