### ISSUE TITLE
Documentation needs at least a simple example

### ISSUE THREAD

**Issue by pablochacin** [tinylib/msgp#96]
There's not a single example of how to use the msgp package. Not even a reference to other source for documentation.

**Comment by ttacon** [comment]
I could agree examples are a little light, but they do exist. There are a couple spots where it's shown how to use msgp with `go generate` and invoking the command manually is explained [here](https://github.com/tinylib/msgp/wiki/Using-the-Code-Generator#invoking-the-generator-manually) in the wiki (with the flags explained [here](https://github.com/tinylib/msgp/wiki/Using-the-Code-Generator#options)).

What kind of examples were you looking for specifically? More of a full walk-through?

**Comment by philhofer** [comment]
Closing this as a duplicate of #78
